Vagrant.configure("2") do |config|

  config.vm.box = "fedora/34-cloud-base"

  config.vm.network :public_network

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "2048"
    virtualbox.cpus = "2"
  end  

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end

end