# https://stackoverflow.com/questions/52578270/install-python-with-cmd-or-powershell/52578838
# https://techexpert.tips/powershell/powershell-open-port-firewall/
# New-NetFirewallRule -DisplayName "ALLOW TCP PORT 80" -Direction inbound -Profile Any -Action Allow -LocalPort 80 -Protocol TCP


Vagrant.configure("2") do |config|

  config.vm.box = "peru/windows-server-2019-standard-x64-eval"
  config.vm.box_version = "20210701.01"
  config.vm.network :public_network 
  config.vm.provision :shell,  privileged: true, path: "shell/install_chocolatey.cmd"
  config.vm.provision :shell,  privileged: true, path: "shell/install_python.cmd"
  config.vm.provision :shell,  privileged: true, path: "shell/configure_firewall.cmd"

end
