# https://stackoverflow.com/questions/52578270/install-python-with-cmd-or-powershell/52578838
# https://techexpert.tips/powershell/powershell-open-port-firewall/
# New-NetFirewallRule -DisplayName "ALLOW TCP PORT 80" -Direction inbound -Profile Any -Action Allow -LocalPort 80 -Protocol TCP
# https://stackoverflow.com/questions/5458048/how-can-i-make-a-python-script-standalone-executable-to-run-without-any-dependen

Vagrant.configure("2") do |config|

  config.vm.box = "peru/windows-server-2019-standard-x64-eval"
  config.vm.box_version = "20210701.01"
  config.vm.network :public_network 
  config.vm.provision :shell,  privileged: true, path: "shell/install_chocolatey.cmd"
  config.vm.provision :shell,  privileged: true, path: "shell/install_python.cmd"
  config.vm.provision :shell,  privileged: true, path: "shell/configure_firewall.cmd"
  config.vm.provision "file", source: "shell/tcp-server.py", destination: "C:\\tmp\\tcp-server.py"
  config.vm.provision :shell,  privileged: true, path: "shell/create_tcp_server_package.cmd"
  config.vm.provision :shell,  privileged: true, path: "shell/install_tcp_server.cmd"

end