Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/groovy64"

  config.vm.network :public_network

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "4096"
    virtualbox.cpus = "4"
  end  

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end

end